//! Code generation: one Rust struct per sheet (PARAM type) and one strut (struct literal) per
//! sheet row, written to `crates/acvd-data/src/generated`. Every value comes from the verified
//! JSON sheets; nothing here supplies data of its own.

use std::collections::HashSet;
use std::fmt::Write as _;

use acvd_formats::layout::{Prim, NON_FINITE_PREFIX};
use anyhow::{bail, ensure, Context, Result};
use serde_json::Value;

use crate::model::*;
use crate::names::{pascal, shouty};

const HEADER: &str = "// @generated by `acvd-sheets gen` from private/sheets/json. Do not edit: fix the sheets and regenerate.\n";

pub fn run(paths: &Paths) -> Result<()> {
    let groups = load_groups(paths)?;
    let out = paths.generated();
    if out.is_dir() {
        std::fs::remove_dir_all(&out)?;
    }
    std::fs::create_dir_all(&out)?;

    let mut module = String::from(HEADER);
    let (mut structs, mut statics, mut struts) = (0, 0, 0);
    for g in &groups {
        let mut src = String::from(HEADER);
        writeln!(src, "#![allow(clippy::all, clippy::pedantic)]\n\nuse crate::Row;\n")?;
        let mut used = HashSet::new();
        for t in &g.tables {
            let (n_statics, n_struts) = table(&mut src, t, &mut used).with_context(|| format!("{}/{}", g.group, t.param_type))?;
            structs += 1;
            statics += n_statics;
            struts += n_struts;
        }
        std::fs::write(out.join(format!("{}.rs", g.group)), src)?;
        writeln!(module, "pub mod {};", g.group)?;
    }
    let assets = assets(paths, &out)?;
    let textures = textures(paths, &out)?;
    let model_groups = load_model_groups(paths)?;
    let models = models(&model_groups, &out)?;
    let (parts, slots) = assembly(paths, &out, &groups, &model_groups)?;
    let (tuning_fields, tuning_named) = tuning(paths, &out)?;
    let calc = ctrl(paths, &out, &groups)?;
    writeln!(module, "pub mod assembly;\npub mod assets;\npub mod ctrl;\npub mod models;\npub mod textures;\npub mod tuning;")?;
    std::fs::write(out.join("mod.rs"), module)?;
    println!(
        "gen: {structs} structs, {statics} file tables, {struts} row struts, {assets} asset struts, {textures} texture struts, {models} model struts, {parts} AC part struts, {slots} slot struts, {tuning_fields} tuning field struts ({tuning_named} named), {calc} AC control values -> {}",
        out.display()
    );
    Ok(())
}

/// `AcCtrlParam`: one field per `sheets/ac_ctrl_calc.csv` row, and `calculate`, which evaluates
/// the rows in order for one design of the `design_parts.csv` table.
fn ctrl(paths: &Paths, out: &std::path::Path, groups: &[GroupSheet]) -> Result<usize> {
    let mut scope = crate::calc::Scope::load(paths)?;
    let rows: Vec<AcCtrlRow> = read_csv(&paths.sheets().join("ac_ctrl_calc.csv"))?;
    let table = scope.columns().first().map(|c| c.table.clone()).context("design_parts.csv is empty")?;
    ensure!(scope.columns().iter().all(|c| c.table == table), "design_parts.csv names more than one table");
    let group = groups.iter().find(|g| g.tables.iter().any(|t| t.param_type == table)).with_context(|| format!("no table {table}"))?;
    let ty = pascal(&table);
    let mut src = String::from(HEADER);
    writeln!(src, "#![allow(clippy::all, clippy::pedantic, unused_parens)]\n\nuse crate::generated::{}::{ty};\n", group.group)?;
    writeln!(src, "/// An AC's control parameters (`sheets/ac_ctrl_calc.csv`), from its `{ty}` parts.\n#[derive(Debug, Clone, Copy, PartialEq)]\npub struct AcCtrlParam {{")?;
    let mut body = String::new();
    for r in &rows {
        let code = scope.translate(&r.expr).map_err(|e| anyhow::anyhow!("ac_ctrl_calc.csv {}: {e}", r.name))?;
        let param = if r.param == crate::preflight::NONE_PARAM { String::new() } else { format!(" (Scr_SetParam {})", r.param) };
        writeln!(src, "    /// {}{param}: {}\n    pub {}: f32,", r.unit, doc(&r.evidence), r.name)?;
        writeln!(body, "        let {}: f32 = {code};", r.name)?;
        scope.defined.push(r.name.clone());
    }
    let names: Vec<&str> = rows.iter().map(|r| r.name.as_str()).collect();
    let parts: Vec<String> = scope.columns().iter().map(|c| format!("(d.{} as i64, {})", c.column, c.category)).collect();
    writeln!(
        src,
        "}}\n\nimpl AcCtrlParam {{\n    /// Whether every part `calculate` reads is catalogued (`sheets/unbuildable_designs.csv` lists the designs that are not).\n    pub fn buildable(d: &{ty}) -> bool {{\n        [{}].iter().all(|&(id, category)| id <= 0 || u16::try_from(id).is_ok_and(|id| crate::ac_part(category, id).is_some()))\n    }}\n\n    pub fn calculate(d: &{ty}) -> Self {{\n{body}        Self {{ {} }}\n    }}\n}}",
        parts.join(", "),
        names.join(", ")
    )?;
    std::fs::write(out.join("ctrl.rs"), src)?;
    Ok(rows.len())
}

fn tuning_type(kind: &str) -> Result<&'static str> {
    Ok(match kind {
        "s8" => "i8",
        "u8" => "u8",
        "s16" => "i16",
        "u16" => "u16",
        "s32" => "i32",
        "u32" => "u32",
        "f32" => "f32",
        _ => bail!("unknown tuning field kind `{kind}`"),
    })
}

fn tuning_literal(kind: &str, v: f64) -> Result<String> {
    Ok(if kind == "f32" { float_literal(&serde_json::json!(v as f32))? } else { format!("{}", v as i64) })
}

/// `TUNING` (one `TuningField` strut per field of every paramlist tuning file) and, per file
/// with rows in `sheets/tuning_fields.csv`, a struct of those fields and its static.
fn tuning(paths: &Paths, out: &std::path::Path) -> Result<(usize, usize)> {
    let sheet: TuningSheet = read_json(&paths.tuning())?;
    let named: Vec<TuningFieldRow> = read_csv(&paths.sheets().join("tuning_fields.csv"))?;
    let mut src = String::from(HEADER);
    writeln!(src, "#![allow(clippy::all, clippy::pedantic)]\n\nuse crate::{{TuningField, TuningFile}};\n")?;
    writeln!(src, "/// Every `<Bin>`/`<Dbp>` pair in `system/paramlist.xml`, fields in file order.\npub static TUNING: &[TuningFile] = &[")?;
    let mut count = 0;
    for f in &sheet.files {
        ensure!(f.error.is_none(), "{} was not decoded", f.bin);
        writeln!(src, "    TuningFile {{ name: {:?}, desc: {:?}, bin: {:?}, fields: &[", f.name, f.desc, f.bin)?;
        for v in &f.fields {
            ensure!(v.value.is_finite(), "{} field `{}` is not finite", f.bin, v.label);
            writeln!(src, "        TuningField {{ label: {:?}, format: {:?}, value: {:?} }},", v.label, v.format, v.value)?;
            count += 1;
        }
        writeln!(src, "    ] }},")?;
    }
    writeln!(src, "];\n")?;
    for f in &sheet.files {
        let rows: Vec<&TuningFieldRow> = named.iter().filter(|n| n.file == f.bin).collect();
        if rows.is_empty() {
            continue;
        }
        let ty = pascal(&f.name);
        writeln!(src, "/// Named fields of `{}` ({}).\n#[derive(Debug, Clone, Copy, PartialEq)]\npub struct {ty} {{", f.bin, f.desc)?;
        let mut values = Vec::new();
        for n in &rows {
            let v = f.fields.get(n.index).with_context(|| format!("{} has no field {}", f.bin, n.index))?;
            writeln!(src, "    /// #{} {} ({})\n    pub {}: {},", n.index, doc(&v.label), n.unit, n.ident, tuning_type(&v.kind)?)?;
            values.push(format!("{}: {}", n.ident, tuning_literal(&v.kind, v.value)?));
        }
        writeln!(src, "}}\n\npub static {}: {ty} = {ty} {{ {} }};\n", shouty(&f.name), values.join(", "))?;
    }
    std::fs::write(out.join("tuning.rs"), src)?;
    Ok((count, named.len()))
}

const MAIN_FACE_SET_EXCLUDES: u32 = 0x0100_0000 | 0x0200_0000 | 0x8000_0000;

/// One `ModelRef` strut per readable FLVER, one static per model group, plus `ALL`.
fn models(groups: &[ModelGroup], out: &std::path::Path) -> Result<usize> {
    let mut src = String::from(HEADER);
    writeln!(src, "#![allow(clippy::all, clippy::pedantic)]\n\nuse crate::{{Joint, ModelRef, Socket}};\n")?;
    let mut statics = Vec::new();
    let mut count = 0;
    for g in groups {
        let name = shouty(&g.group);
        writeln!(src, "/// FLVER models under `{}/`.", g.group)?;
        writeln!(src, "pub static {name}: &[ModelRef] = &[")?;
        for m in g.models.iter().filter(|m| m.error.is_none()) {
            let triangles: usize = m
                .meshes
                .iter()
                .filter_map(|mesh| mesh.face_sets.iter().find(|f| f.flags & MAIN_FACE_SET_EXCLUDES == 0).or(mesh.face_sets.first()))
                .map(|f| f.triangles)
                .sum();
            let vertices: usize = m.meshes.iter().map(|x| x.vertices).sum();
            let mut textures: Vec<String> = m
                .materials
                .iter()
                .flat_map(|x| &x.textures)
                .filter(|(_, p)| !p.is_empty())
                .map(|(_, p)| {
                    let file = p.rsplit(['\\', '/']).next().unwrap_or(p);
                    file.split('.').next().unwrap_or(file).to_owned()
                })
                .collect();
            textures.sort_by_key(|t| t.to_ascii_lowercase());
            textures.dedup_by(|a, b| a.eq_ignore_ascii_case(b));
            let roots: Vec<String> = m
                .skeleton
                .iter()
                .filter(|b| b.parent < 0)
                .map(|b| format!("Joint {{ name: {:?}, origin: {:?} }}", b.name, b.origin))
                .collect();
            let mut sockets = Vec::new();
            for s in m.sockets.iter().filter(|s| s.color[0] != 0) {
                let root = usize::try_from(s.bone).ok().and_then(|b| m.root_of(b)).with_context(|| format!("{} socket {} has no root bone", m.path, s.color[0]))?;
                sockets.push(format!("Socket {{ id: {}, root: {root:?}, position: {:?} }}", s.color[0], s.position));
            }
            writeln!(
                src,
                "    ModelRef {{ path: {:?}, version: {:#x}, meshes: {}, vertices: {vertices}, triangles: {triangles}, bbox_min: {:?}, bbox_max: {:?}, textures: &{textures:?}, roots: &[{}], sockets: &[{}] }},",
                m.path,
                m.version,
                m.meshes.len(),
                m.bbox_min,
                m.bbox_max,
                roots.join(", "),
                sockets.join(", ")
            )?;
            count += 1;
        }
        writeln!(src, "];\n")?;
        statics.push(name);
    }
    writeln!(src, "/// Every model group.")?;
    writeln!(src, "pub static ALL: &[&[ModelRef]] = &[{}];", statics.join(", "))?;
    std::fs::write(out.join("models.rs"), src)?;
    Ok(count)
}

/// `AC_PARTS` (one strut per `acvparts.bin` record, with the models it resolves to) and one
/// `Slot` strut per `sheets/assembly_slots.csv` row.
fn assembly(paths: &Paths, out: &std::path::Path, groups: &[GroupSheet], models: &[ModelGroup]) -> Result<(usize, usize)> {
    let categories: Vec<AcPartCategoryRow> = read_csv(&paths.sheets().join("ac_part_categories.csv"))?;
    let slots: Vec<AssemblySlotRow> = read_csv(&paths.sheets().join("assembly_slots.csv"))?;
    let parts: AcPartsSheet = read_json(&paths.ac_parts())?;
    let readable: HashSet<&str> = models.iter().flat_map(|g| &g.models).filter(|m| m.error.is_none()).map(|m| m.path.as_str()).collect();

    let mut src = String::from(HEADER);
    writeln!(src, "#![allow(clippy::all, clippy::pedantic)]\n\nuse crate::{{AcMotion, AcPart, AcState, Slot, SocketRef}};")?;
    let mut tables: Vec<(&GroupSheet, &TableSheet)> = Vec::new();
    for s in &slots {
        let t = groups.iter().flat_map(|g| g.tables.iter().map(move |t| (g, t))).find(|(_, t)| t.param_type == s.table).with_context(|| format!("slot {}: no table {}", s.slot, s.table))?;
        if !tables.iter().any(|(_, x)| x.param_type == t.1.param_type) {
            writeln!(src, "use crate::generated::{}::{};", t.0.group, pascal(&t.1.param_type))?;
            tables.push(t);
        }
    }

    writeln!(src, "\n/// `param/acvparts.bin`, in file order.\npub static AC_PARTS: &[AcPart] = &[")?;
    for r in &parts.records {
        let c = categories.iter().find(|c| c.category == r.category).with_context(|| format!("category {} has no sheet row", r.category))?;
        let found: Vec<String> = c
            .prefixes()
            .map(|p| (p, c.model_path(p, r.model_id)))
            .filter(|(_, path)| readable.contains(path.as_str()))
            .map(|(p, path)| format!("({p:?}, {path:?})"))
            .collect();
        let fields: Vec<String> = r.fields.iter().map(|(k, v)| format!("({k:?}, {v:?})")).collect();
        writeln!(src, "    AcPart {{ category: {}, id: {}, model_id: {}, models: &[{}], fields: &[{}] }},", r.category, r.id, r.model_id, found.join(", "), fields.join(", "))?;
    }
    writeln!(src, "];\n")?;

    for (_, t) in &tables {
        let ty = pascal(&t.param_type);
        writeln!(src, "/// Where each `{ty}` column's part attaches, parents first.\npub static {}_SLOTS: &[Slot<{ty}>] = &[", shouty(&t.param_type))?;
        for s in slots.iter().filter(|s| s.table == t.param_type) {
            let socket = match crate::preflight::socket_spec(&s.socket).with_context(|| format!("slot {}: bad socket", s.slot))? {
                crate::preflight::SocketSpec::None => "SocketRef::None".to_owned(),
                crate::preflight::SocketSpec::Dummy(id) => format!("SocketRef::Dummy({id})"),
                crate::preflight::SocketSpec::Bone(b) => format!("SocketRef::Bone({b:?})"),
            };
            let parent = if s.parent == crate::preflight::NONE { "None".to_owned() } else { format!("Some({:?})", s.parent) };
            let roots: Vec<&str> = if s.root.trim() == ALL_ROOTS { Vec::new() } else { s.root.split(';').map(str::trim).collect() };
            let orient = match s.orient.trim() {
                "" | "none" => "None".to_owned(),
                n => {
                    let v: u8 = n.parse().with_context(|| format!("slot {}: orient `{n}` is not none or a flag byte", s.slot))?;
                    format!("Some({v})")
                }
            };
            writeln!(
                src,
                "    Slot {{ name: {:?}, column: {:?}, part: |a| a.{} as i64, category: {}, prefix: {:?}, parent: {parent}, socket: {socket}, roots: &{roots:?}, orient: {orient} }},",
                s.slot, s.column, s.column, s.category, s.prefix
            )?;
        }
        writeln!(src, "];\n")?;
    }

    writeln!(src, "/// The motion set each part of an `ac_motion.csv` slot selects.\npub static AC_MOTIONS: &[AcMotion] = &[")?;
    for p in crate::motions::part_motions(paths)? {
        let Ok((set, clip)) = p.set else { continue };
        writeln!(src, "    AcMotion {{ category: {}, id: {}, set: {set:?}, skeleton: {clip:?} }},", p.category, p.id)?;
    }
    writeln!(src, "];\n")?;

    let states: Vec<AcStateRow> = read_csv(&paths.sheets().join("ac_states.csv"))?;
    writeln!(src, "/// Locomotion states and the `{}` row each plays (`sheets/ac_states.csv`).\npub static AC_STATES: &[AcState] = &[", crate::preflight::AC_MOTION_FILE)?;
    for s in &states {
        let direction = s.direction.map_or("None".to_owned(), |d| format!("Some({d})"));
        writeln!(src, "    AcState {{ state: {:?}, direction: {direction}, row: {} }},", s.state, s.row)?;
    }
    writeln!(src, "];")?;
    std::fs::write(out.join("assembly.rs"), src)?;
    Ok((parts.records.len(), slots.len()))
}

/// `TEXTURE_FORMATS` from `sheets/texture_formats.csv`, then one `TextureRef` strut per TPF texture.
fn textures(paths: &Paths, out: &std::path::Path) -> Result<usize> {
    let mut src = String::from(HEADER);
    writeln!(src, "#![allow(clippy::all, clippy::pedantic)]\n\nuse crate::{{TextureFormat, TextureRef}};\n")?;
    let formats: Vec<TextureFormatRow> = read_csv(&paths.sheets().join("texture_formats.csv"))?;
    writeln!(src, "/// TPF format codes on the disc (`sheets/texture_formats.csv`).")?;
    writeln!(src, "pub static TEXTURE_FORMATS: &[TextureFormat] = &[")?;
    for f in &formats {
        writeln!(src, "    TextureFormat {{ code: {}, name: {:?}, block_bytes: {} }},", f.code, f.name, f.block_bytes)?;
    }
    writeln!(src, "];\n")?;
    let mut statics = Vec::new();
    let mut count = 0;
    for g in load_texture_groups(paths)? {
        let name = shouty(&g.group);
        writeln!(src, "/// Textures in TPFs under `{}/`.", g.group)?;
        writeln!(src, "pub static {name}: &[TextureRef] = &[")?;
        for p in &g.packs {
            ensure!(p.error.is_none(), "{} was not decoded", p.path);
            for t in &p.textures {
                writeln!(
                    src,
                    "    TextureRef {{ pack: {:?}, index: {}, name: {:?}, format: {}, width: {}, height: {}, levels: {}, faces: {}, size: {} }},",
                    p.path, t.index, t.name, t.format, t.width, t.height, t.levels, t.faces, t.size
                )?;
                count += 1;
            }
        }
        writeln!(src, "];\n")?;
        statics.push(name);
    }
    writeln!(src, "/// Every texture group.")?;
    writeln!(src, "pub static ALL: &[&[TextureRef]] = &[{}];", statics.join(", "))?;
    std::fs::write(out.join("textures.rs"), src)?;
    Ok(count)
}

/// One `Asset` strut per binder entry, one static per archive group, plus `ALL`.
fn assets(paths: &Paths, out: &std::path::Path) -> Result<usize> {
    let mut src = String::from(HEADER);
    writeln!(src, "#![allow(clippy::all, clippy::pedantic)]\n\nuse crate::Asset;\n")?;
    let mut statics = Vec::new();
    let mut count = 0;
    for g in load_archive_groups(paths)? {
        let name = shouty(&g.group);
        writeln!(src, "/// Binder entries under `{}/`.", g.group)?;
        writeln!(src, "pub static {name}: &[Asset] = &[")?;
        for b in &g.binders {
            let mut seen = std::collections::HashMap::new();
            for e in &b.entries {
                *seen.entry(e.name.as_deref()).or_insert(0) += 1;
            }
            for e in &b.entries {
                let entry_name = e.name.as_deref().with_context(|| format!("{} #{} has no name", b.path, e.index))?;
                ensure!(e.error.is_none(), "{} #{} was not decoded", b.path, e.index);
                let entry = if seen[&e.name.as_deref()] > 1 { format!("#{}", e.index) } else { entry_name.to_owned() };
                let id = e.id.map_or("None".into(), |v| format!("Some({v})"));
                writeln!(
                    src,
                    "    Asset {{ binder: {:?}, entry: {entry:?}, name: {entry_name:?}, id: {id}, size: {}, ext: {:?} }},",
                    b.path, e.size, e.ext
                )?;
                count += 1;
            }
        }
        writeln!(src, "];\n")?;
        statics.push(name);
    }
    writeln!(src, "/// Every archive group.")?;
    writeln!(src, "pub static ALL: &[&[Asset]] = &[{}];", statics.join(", "))?;
    std::fs::write(out.join("assets.rs"), src)?;
    Ok(count)
}

fn rust_type(c: &Column) -> Result<String> {
    let prim = Prim::parse(c.prim.as_deref().unwrap_or_default()).with_context(|| format!("column #{} has no type", c.index))?;
    let scalar = match prim {
        Prim::U8 | Prim::Dummy8 => "u8",
        Prim::S8 => "i8",
        Prim::U16 => "u16",
        Prim::S16 => "i16",
        Prim::U32 => "u32",
        Prim::S32 => "i32",
        Prim::F32 | Prim::Angle32 => "f32",
        Prim::FixStr | Prim::FixStrW => return Ok("&'static str".into()),
    };
    Ok(if c.bits.is_some() || (c.count == 1 && prim != Prim::Dummy8) { scalar.into() } else { format!("[{scalar}; {}]", c.count) })
}

fn float_literal(v: &Value) -> Result<String> {
    if let Some(bits) = v.as_str().and_then(|s| s.strip_prefix(NON_FINITE_PREFIX)) {
        return Ok(format!("f32::from_bits(0x{bits})"));
    }
    let f = v.as_f64().with_context(|| format!("expected a float, got {v}"))? as f32;
    let s = format!("{f:?}");
    Ok(if s.contains(['.', 'e', 'E']) { s } else { format!("{s}.0") })
}

fn scalar_literal(prim: Prim, v: &Value) -> Result<String> {
    if prim.is_float() {
        return float_literal(v);
    }
    let n = v.as_i64().with_context(|| format!("expected an integer, got {v}"))?;
    Ok(n.to_string())
}

fn literal(c: &Column, v: &Value) -> Result<String> {
    let prim = Prim::parse(c.prim.as_deref().unwrap_or_default()).context("untyped column")?;
    if c.bits.is_some() {
        return scalar_literal(Prim::U32, v);
    }
    match prim {
        Prim::FixStr | Prim::FixStrW => Ok(format!("{:?}", v.as_str().with_context(|| format!("expected text, got {v}"))?)),
        Prim::Dummy8 => {
            let hex = v.as_str().with_context(|| format!("expected hex bytes, got {v}"))?;
            let bytes: Vec<String> = hex.split_whitespace().map(|b| format!("0x{b}")).collect();
            ensure!(bytes.len() == c.count, "dummy8 column #{} has {} bytes, sheet says {}", c.index, bytes.len(), c.count);
            Ok(format!("[{}]", bytes.join(", ")))
        }
        _ if c.count == 1 => scalar_literal(prim, v),
        _ => {
            let items = v.as_array().with_context(|| format!("expected a list, got {v}"))?;
            ensure!(items.len() == c.count, "column #{} has {} items, sheet says {}", c.index, items.len(), c.count);
            Ok(format!("[{}]", items.iter().map(|x| scalar_literal(prim, x)).collect::<Result<Vec<_>>>()?.join(", ")))
        }
    }
}

fn doc(s: &str) -> String {
    s.lines().map(str::trim).filter(|l| !l.is_empty()).collect::<Vec<_>>().join(" ")
}

fn table(src: &mut String, t: &TableSheet, used: &mut HashSet<String>) -> Result<(usize, usize)> {
    let ty = pascal(&t.param_type);
    ensure!(used.insert(ty.clone()), "struct name `{ty}` collides");

    writeln!(src, "/// `{}` from `{}` (PARAMDEF format {}).", t.param_type, t.def_file, t.def_format_version)?;
    writeln!(src, "#[derive(Debug, Clone, Copy, PartialEq)]\npub struct {ty} {{")?;
    let mut fields = Vec::with_capacity(t.columns.len());
    for c in &t.columns {
        let ident = c.ident.clone().with_context(|| format!("column #{} has no identifier", c.index))?;
        let label = doc(&c.display_name);
        if !label.is_empty() {
            writeln!(src, "    /// {label}")?;
        }
        writeln!(src, "    pub {ident}: {},", rust_type(c)?)?;
        fields.push(ident);
    }
    writeln!(src, "}}\n")?;

    let mut files = Vec::new();
    let mut struts = 0;
    for inst in &t.instances {
        let name = shouty(&inst.id);
        if !used.insert(name.clone()) {
            bail!("static name `{name}` from `{}` collides", inst.file);
        }
        writeln!(src, "/// `{}`", inst.file)?;
        writeln!(src, "pub static {name}: &[Row<{ty}>] = &[")?;
        for r in &inst.rows {
            let values = r.values.as_ref().with_context(|| format!("{} row {} was not decoded", inst.file, r.id))?;
            ensure!(values.len() == t.columns.len(), "{} row {} has {} values", inst.file, r.id, values.len());
            write!(src, "    Row {{ id: {}, name: {:?}, data: {ty} {{", r.id, r.name)?;
            for ((c, v), f) in t.columns.iter().zip(values).zip(&fields) {
                write!(src, " {f}: {},", literal(c, v).with_context(|| format!("{} row {} column {f}", inst.file, r.id))?)?;
            }
            writeln!(src, " }} }},")?;
            struts += 1;
        }
        writeln!(src, "];\n")?;
        files.push((inst.file.clone(), name));
    }

    let index = format!("{}_FILES", shouty(&t.param_type));
    ensure!(used.insert(index.clone()), "index name `{index}` collides");
    writeln!(src, "/// Every `{}` file on the disc.", t.param_type)?;
    writeln!(src, "pub static {index}: &[(&str, &[Row<{ty}>])] = &[")?;
    for (file, name) in &files {
        writeln!(src, "    ({file:?}, {name}),")?;
    }
    writeln!(src, "];\n")?;
    Ok((files.len(), struts))
}
